<a href="https://colab.research.google.com/github/sinnooooosuke/python_brushup/blob/main/python_brushup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 始める前に実行

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Python基礎（途中から）

## 辞書
キーとそれに対応する要素がセットになったもの。

In [ ]:
#キーとそれに対応する要素がセット

dic = {'a':100, 'b':200}
print(dic['a'])

100

In [ ]:
# 空の辞書
empty_dic = {}

In [ ]:
#キーの検索
'a' in dic

True

In [ ]:
#キーと要素の追加
dic['c'] = 300
dic

{'a': 100, 'b': 200, 'c': 300}

In [ ]:
#keysメソッド
for k in dic.keys():
    print(k, dic[k])

a 100
b 200
c 300

In [ ]:
#itemsメソッド
for k, v in dic.items():
    print(k, v)

a 100
b 200
c 300

# ライブラリ

## ライブラリの使い方

In [ ]:
# ライブラリのインポート
import statistics

In [ ]:
data=[2,4,7,7,8,3,7,5]
statistics.mean(data)

5.375

In [ ]:
#fromを使うと関数名の頭にライブラリ名を入れなくても良い(省略)
#別名（略称）を使うことも可能

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
np.pi

3.141592653589793

In [ ]:
# インポートする前にインストールする必要があるかもよ
# ノートブックではpipコマンドを使おう

## pandas

NumPyの上に築かれたデータ分析用のライブラリ。
ベクトル化して楽にな〜る。

データの形（オブジェクトの種類）：シリーズ・データフレーム

In [ ]:
# リストからシリーズを作る
ser = pd.Series([10,20,30,40])
ser

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# リストからデータフレームを作る
df = pd.DataFrame([[10,'a'],[20,'b'],[30,'c'],[40,'d']])
print(df)

    0  1
0  10  a
1  20  b
2  30  c
3  40  d

In [ ]:
# pd.read_csvでcsvファイルを読み込むこともできる
URL = '/content/drive/MyDrive/projects/python_data_analysis/SSDSE-E-2025.csv'

df = pd.read_csv(URL, skiprows=[0,1,3],
                 encoding='shift_jis')
df

,地域コード,都道府県,総人口,日本人人口,15歳未満人口,15〜64歳人口,65歳以上人口,外国人人口,出生数,合計特殊出生率,...,歯科診療所数,医師数,歯科医師数,薬剤師数,保育所等数,保育所等在所児数,消費支出（二人以上の世帯）,食料費（二人以上の世帯）,住居費（二人以上の世帯）,教養娯楽費（二人以上の世帯）
0,R01000,北海道,5092000,5041000,514000,2897000,1681000,34321,26407,1.12,...,2784,13613,4302,11625,1099,79262,296888,74341,26730,25661
1,R02000,青森県,1184000,1177000,118000,649000,417000,5409,5985,1.24,...,493,2795,715,2373,472,29676,263371,77899,14433,20630
2,R03000,岩手県,1163000,1154000,120000,636000,407000,6937,5788,1.21,...,548,2758,965,2572,391,27461,298536,81997,18598,28499
3,R04000,宮城県,2264000,2239000,250000,1352000,662000,19453,12852,1.09,...,1054,6140,1921,5570,515,38360,305541,83835,21914,27380
4,R05000,秋田県,914000,909000,83000,474000,357000,3651,3992,1.18,...,424,2438,600,2055,268,21624,272086,78124,11954,23175
5,R06000,山形県,1026000,1018000,109000,556000,361000,7149,5674,1.32,...,468,2625,691,2174,302,24018,322992,84105,20613,26661
6,R07000,福島県,1767000,1751000,190000,990000,586000,12868,9709,1.27,...,834,4096,1398,3791,391,33563,307186,78984,22159,28081
7,R08000,茨城県,2825000,2744000,312000,1647000,865000,57819,15905,1.27,...,1364,6029,1918,6709,629,56911,307817,75270,18701,28065
8,R09000,栃木県,1897000,1848000,210000,1114000,573000,37408,10518,1.24,...,959,4949,1373,4376,439,39031,325226,87797,17432,32045
9,R10000,群馬県,1902000,1831000,210000,1103000,589000,53432,10688,1.32,...,976,4657,1344,4157,468,45462,283599,76203,17966,27095
10,R11000,埼玉県,7331000,7113000,831000,4489000,2012000,161439,43451,1.17,...,3542,13661,5410,16729,1514,125112,344092,93279,13823,34358
11,R12000,千葉県,6257000,6081000,703000,3798000,1756000,142177,36966,1.18,...,3241,13521,4953,14746,1329,102287,306943,89043,18625,31683
12,R13000,東京都,14086000,13448000,1513000,9368000,3205000,483372,91097,1.04,...,10696,48578,16890,53527,3615,275851,341320,97776,26457,40393
13,R14000,神奈川県,9229000,8970000,1031000,5808000,2390000,195535,56498,1.17,...,4983,21421,7314,23718,2053,162670,306565,87320,11639,36781
14,R15000,新潟県,2126000,2107000,228000,1179000,720000,15028,11732,1.27,...,1117,4894,2002,4563,714,59330,301215,82712,24071,25310
15,R16000,富山県,1007000,987000,108000,566000,333000,16326,6022,1.46,...,439,2889,635,2932,297,28821,327503,86794,19413,25900
16,R17000,石川県,1109000,1091000,128000,643000,338000,13685,7075,1.38,...,479,3390,734,2853,346,33485,306536,86611,14674,31999
17,R18000,福井県,744000,729000,89000,421000,235000,13796,4861,1.50,...,300,2132,446,1500,289,24337,276690,75825,13596,25844
18,R19000,山梨県,796000,776000,87000,456000,253000,13993,4759,1.40,...,429,2148,600,1861,233,18339,297715,78204,17630,25664
19,R20000,長野県,2004000,1965000,228000,1120000,655000,31491,12143,1.43,...,991,5290,1654,4667,562,47111,313991,79401,15655,31189
20,R21000,岐阜県,1931000,1868000,224000,1104000,603000,48979,11124,1.36,...,949,4630,1717,4108,415,36543,320779,76644,12770,25924
21,R22000,静岡県,3555000,3449000,404000,2050000,1101000,86046,20575,1.33,...,1743,8535,2371,8403,693,65191,300652,85135,19678,28942
22,R23000,愛知県,7477000,7195000,927000,4627000,1923000,231369,51152,1.35,...,3703,18516,6063,16239,1582,156689,300221,88312,13435,30824
23,R24000,三重県,1727000,1669000,198000,999000,529000,44721,10489,1.40,...,805,4395,1138,3607,426,38489,332663,81408,20307,33346
24,R25000,滋賀県,1407000,1367000,182000,844000,380000,28704,9766,1.43,...,564,3575,828,3359,337,34119,305586,83265,13467,30228
25,R26000,京都府,2535000,2465000,275000,1507000,753000,52442,15068,1.18,...,1281,9067,1965,6806,512,53838,314636,85900,23779,29737
26,R27000,大阪府,8763000,8488000,984000,5355000,2424000,208681,57315,1.22,...,5468,26518,7954,27586,1595,163302,271246,85042,20861,25851
27,R28000,兵庫県,5370000,5247000,629000,3132000,1609000,87280,33565,1.31,...,2960,15602,4145,15594,1113,105663,279880,85960,16138,29444
28,R29000,奈良県,1296000,1279000,145000,728000,423000,11505,7315,1.25,...,682,3868,949,3219,223,24389,313833,85274,11799,30883
29,R30000,和歌山県,892000,884000,99000,488000,305000,6029,5238,1.39,...,520,3010,698,2346,192,19912,259437,74738,15699,22743
30,R31000,鳥取県,537000,532000,65000,294000,179000,4310,3752,1.60,...,258,1878,383,1243,187,16514,272599,73150,12297,26546
31,R32000,島根県,650000,640000,77000,346000,227000,8230,4161,1.57,...,251,2153,398,1451,297,20644,294837,76446,15875,24889
32,R33000,岡山県,1847000,1814000,220000,1054000,573000,25116,12371,1.39,...,995,6271,1764,4245,456,44721,300973,81556,13911,29238
33,R34000,広島県,2738000,2682000,331000,1582000,825000,47733,17903,1.40,...,1502,7870,2508,7324,698,60603,305373,83473,27143,26681
34,R35000,山口県,1298000,1279000,143000,696000,459000,14378,7762,1.47,...,641,3737,951,3524,301,23104,286970,76261,18111,27750
35,R36000,徳島県,695000,688000,74000,376000,246000,5033,4148,1.42,...,422,2478,833,2595,213,16038,301013,74957,18894,29700
36,R37000,香川県,926000,910000,107000,517000,301000,10854,5802,1.45,...,473,2846,703,2429,223,21738,286800,77148,14542,26394
37,R38000,愛媛県,1291000,1277000,143000,707000,441000,11159,7572,1.39,...,646,3888,919,3186,311,24227,223423,71088,17608,18615
38,R39000,高知県,666000,660000,70000,355000,242000,4220,3721,1.36,...,346,2346,459,1792,245,18419,294877,80091,20254,26740
39,R40000,福岡県,5103000,5011000,644000,3007000,1452000,66699,35970,1.33,...,3074,16722,5703,12796,1065,116208,309000,80319,21148,30359
40,R41000,佐賀県,795000,786000,103000,440000,252000,5940,5552,1.53,...,399,2430,619,2013,263,23767,274861,74932,18473,22570
41,R42000,長崎県,1267000,1254000,153000,679000,435000,8316,8364,1.57,...,703,4424,1232,2950,490,36376,262243,76604,19933,18374
42,R43000,熊本県,1709000,1685000,219000,938000,552000,14591,11875,1.52,...,832,5428,1367,3983,623,53101,294537,79939,18740,27571
43,R44000,大分県,1096000,1079000,127000,594000,375000,10168,6798,1.49,...,524,3459,737,2364,336,25785,304631,74200,24838,26562
44,R45000,宮崎県,1042000,1032000,133000,559000,351000,6474,7136,1.63,...,488,2908,734,2288,419,31267,257997,73243,16714,19658
45,R46000,鹿児島県,1549000,1533000,197000,828000,524000,10037,10540,1.54,...,795,4668,1375,3307,584,38795,279132,74045,22957,23766
46,R47000,沖縄県,1468000,1443000,236000,882000,350000,18157,13594,1.70,...,610,4029,889,2435,631,57035,251222,73453,27521,18482

In [ ]:
# インデックスの情報確認
df.index

RangeIndex(start=0, stop=47, step=1)

In [ ]:
#カラムの情報確認
df.columns

Index(['地域コード', '都道府県', '総人口', '日本人人口', '15歳未満人口', '15〜64歳人口', '65歳以上人口',
       '外国人人口', '出生数', '合計特殊出生率', '死亡数', '転入者数（日本人移動者）', '転出者数（日本人移動者）',
       '一般世帯数', '一般世帯人員数', '単独世帯数', '婚姻件数', '離婚件数', '総面積（北方地域及び竹島を除く）',
       '可住地面積', '自然公園面積', '県内総生産額（平成27年基準）', '県民所得（平成27年基準）',
       '1人当たり県民所得（平成27年基準）', '事業所数（民営）', '事業所数（民営）（建設業）', '事業所数（民営）（製造業）',
       '事業所数（民営）（情報通信業）', '事業所数（民営）（卸売業、小売業）', '事業所数（民営）（宿泊業、飲食サービス業）',
       '事業所数（民営）（生活関連サービス業、娯楽業）', '事業所数（民営）（医療、福祉）', '従業者数（民営）',
       '従業者数（民営）（建設業）', '従業者数（民営）（製造業）', '従業者数（民営）（情報通信業）',
       '従業者数（民営）（卸売業、小売業）', '従業者数（民営）（宿泊業、飲食サービス業）', '従業者数（民営）（生活関連サービス業、娯楽業）',
       '従業者数（民営）（医療、福祉）', '農家数（販売農家）', '農家数（自給的農家）', '耕地面積', '旅館営業施設数（ホテルを含む）',
       '旅館営業施設客室数（ホテルを含む）', '幼稚園数', '幼稚園在園者数', '小学校数', '小学校児童数', '中学校数',
       '中学校生徒数', '義務教育学校数', '義務教育学校前期課程児童数', '義務教育学校後期課程生徒数', '高等学校数',
       '高等学校生徒数', '短期大学数', '大学数', '短期大学学生数', '大学学生数', '公民館数', '図書館数', '博物館数',
       '劇場、音楽堂等数', '社会体育施設数', '民間体育施設数', '映画館数', '一般旅券発行件数', '延べ宿泊者数',
       '外国人延べ宿泊者数', '総住宅数', '空き家数', '持ち家数', '一戸建住宅数', '1住宅当たり延べ面積',
       '総人口（非水洗化人口＋水洗化人口）', '非水洗化人口', 'ごみ総排出量（総量）', '1人1日当たりの排出量', 'ごみのリサイクル率',
       '小売店数', '飲食店数', '大型小売店数', '一般病院数', '一般診療所数', '歯科診療所数', '医師数', '歯科医師数',
       '薬剤師数', '保育所等数', '保育所等在所児数', '消費支出（二人以上の世帯）', '食料費（二人以上の世帯）',
       '住居費（二人以上の世帯）', '教養娯楽費（二人以上の世帯）'],
      dtype='object')

In [ ]:
#行の抽出
df[44:47]

,地域コード,都道府県,総人口,日本人人口,15歳未満人口,15〜64歳人口,65歳以上人口,外国人人口,出生数,合計特殊出生率,...,歯科診療所数,医師数,歯科医師数,薬剤師数,保育所等数,保育所等在所児数,消費支出（二人以上の世帯）,食料費（二人以上の世帯）,住居費（二人以上の世帯）,教養娯楽費（二人以上の世帯）
44,R45000,宮崎県,1042000,1032000,133000,559000,351000,6474,7136,1.63,...,488,2908,734,2288,419,31267,257997,73243,16714,19658
45,R46000,鹿児島県,1549000,1533000,197000,828000,524000,10037,10540,1.54,...,795,4668,1375,3307,584,38795,279132,74045,22957,23766
46,R47000,沖縄県,1468000,1443000,236000,882000,350000,18157,13594,1.70,...,610,4029,889,2435,631,57035,251222,73453,27521,18482

In [ ]:
#列の抽出
#複数の場合は列名のリストで指定する
df[['都道府県','一戸建住宅数']]

    都道府県   一戸建住宅数
0    北海道  1258400
1    青森県   368000
2    岩手県   344000
3    宮城県   543200
4    秋田県   293200
5    山形県   297900
6    福島県   512900
7    茨城県   832100
8    栃木県   571100
9    群馬県   589200
10   埼玉県  1729600
11   千葉県  1463400
12   東京都  1900500
13  神奈川県  1740300
14   新潟県   629100
15   富山県   297300
16   石川県   318800
17   福井県   214300
18   山梨県   242100
19   長野県   605000
20   岐阜県   571000
21   静岡県   964200
22   愛知県  1638000
23   三重県   526400
24   滋賀県   382900
25   京都府   635300
26   大阪府  1671500
27   兵庫県  1189600
28   奈良県   366400
29  和歌山県   288100
30   鳥取県   157700
31   島根県   186200
32   岡山県   522800
33   広島県   676500
34   山口県   388300
35   徳島県   210500
36   香川県   265300
37   愛媛県   386600
38   高知県   209500
39   福岡県  1007500
40   佐賀県   214000
41   長崎県   344600
42   熊本県   448800
43   大分県   295700
44   宮崎県   316700
45  鹿児島県   470200
46   沖縄県   234900

In [ ]:
#条件抽出
df[(df['総人口'] <= 1500000) & (df['出生数'] >= 10000)]

,地域コード,都道府県,総人口,日本人人口,15歳未満人口,15〜64歳人口,65歳以上人口,外国人人口,出生数,合計特殊出生率,...,歯科診療所数,医師数,歯科医師数,薬剤師数,保育所等数,保育所等在所児数,消費支出（二人以上の世帯）,食料費（二人以上の世帯）,住居費（二人以上の世帯）,教養娯楽費（二人以上の世帯）
46,R47000,沖縄県,1468000,1443000,236000,882000,350000,18157,13594,1.7,...,610,4029,889,2435,631,57035,251222,73453,27521,18482

In [ ]:
#行と列両方任意のものを抽出するには、loc属性を使う
df.loc[[12,26],['都道府県','総人口','出生数']]

   都道府県       総人口    出生数
12  東京都  14086000  91097
26  大阪府   8763000  57315

## Numpy

配列（array）というデータ構造を提供